# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Free Trial(8bc354b4-f372-41ce-a6c2-856ab22f5fcf)'
    subscriptionId: '8bc354b4-f372-41ce-a6c2-856ab22f5fcf'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rvrg'
    location: 'East Asia'
    templateLocation: 'Linked artifact'
    csmFile: 'DemoApp/Manifest/con_reg_template.json'
    csmParametersFile: 'DemoApp/Manifest/con_reg_parametersFile.json'
    deploymentMode: 'Incremental'
