steps:
- name: "gcr.io/cloud-builders/docker"
#   args: ["build", "-t", "gcr.io/$PROJECT_ID/dotnetcoresample:latest", "."]
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/dotnetcoresample:latest', '-f', 'DemoApp/Dockerfile', '.' ]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/dotnetcoresample:latest"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=DemoApp/Manifest/gke-deployment.yaml
  - --image=gcr.io/$PROJECT_ID/dotnetcoresample:latest
  - --location=us-central1-c
  - --cluster=perfectk8s
