apiVersion: apps/v1
kind: Deployment
metadata:
    name: dotnetcoresample-deployment
    labels:
        app: dotnetcoresample
spec:
    replicas: 1
    selector:
        matchLabels:
            app: dotnetcoresample
    template: 
        metadata:
            labels:
                app: dotnetcoresample
        spec:
            containers:
            - name: k8s-demo
              image: gcr.io/tde-coe-anthos/dotnetcoresample:latest
              ports:
              - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: dotnetcoresample
    labels:
        app: dotnetcoresample
spec:
    ports:
        - name: http-port
          port: 80
          targetPort: 80
    selector: 
        app: dotnetcoresample
    type: LoadBalancer
